Repository andela/Ah-backend-xmen, pull requests merged in 2019-01, with the labels that each got.

#3 #162725244 Upgrade Django version from 1.0 to 2.1.5
  authors/apps/authentication/backends.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/urls.py
  authors/urls.py
  requirements.txt
Labels: finished

#2 #162725251 Integrate coveralls code coverage service
  .coveralls.yml
  README.md
  requirements.txt
Labels: finished

#7 #162725248 Integrate TravisCI with readme badge
  .travis.yml
  README.md
Labels: finished

#4 #162725249 Integrate the application to use a postgresql database
  .gitignore
  authors/apps/authentication/migrations/0001_initial.py
  authors/settings.py
  requirements.txt
  sample_env.txt
Labels: finished

#6 #162725242 Write unit tests for all functionality
  .gitignore
  .travis.yml
  authors/apps/authentication/backends.py
  authors/apps/authentication/models.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests_/__init__.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_endpoints.py
  authors/apps/authentication/tests_/test_model.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/core/exceptions.py
  authors/urls.py
  requirements.txt
Labels: finished

#8 #163112212 Update the README
  .codeclimate.yml
  README.md
Labels: finished

#5 #162725250 Setup and deploy base application to heroku
  .gitignore
  Procfile
  authors/settings.py
  authors/urls.py
  requirements.txt
  static/production/random.txt
Labels: finished

#9 #163117616 Include coveralls in requirement.txt file and clean it up
  requirements.txt
Labels: finished

#13 #162725254 Users should receive descriptive signup validation errors
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_endpoints.py
  authors/apps/authentication/tests_/test_signup_validation.py
Labels: finished, reviews required

#12 #162725256 Users should be able to reset passwords via email
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_data.py
  authors/apps/authentication/tests_/test_endpoints.py
  authors/apps/authentication/tests_/test_signup_validation.py
  authors/apps/authentication/tests_/test_user_endpoints.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/core/models.py
  authors/apps/core/templates/password_reset_email.txt
  authors/apps/utils/__init__.py
  authors/apps/utils/messages.py
  authors/apps/utils/tests/__init__.py
  authors/apps/utils/tests/test_validation_helpers.py
  authors/apps/utils/validators/__init__.py
  authors/apps/utils/validators/validation_helpers.py
  authors/settings.py
  requirements.txt
Labels: finished, reviews required

#15 #162725253 Implement JWT authentication
  authors/apps/authentication/backends.py
  authors/apps/authentication/models.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_endpoints.py
  authors/apps/authentication/tests_/test_jwt_auth.py
  authors/apps/authentication/tests_/test_model.py
  authors/apps/authentication/tests_/test_signup_validation.py
  authors/apps/authentication/views.py
  authors/urls.py
Labels: work in progress

#11 #162725255 Receive email on successful signup
  .codeclimate.yml
  authors/apps/authentication/migrations/0002_auto_20190112_0612.py
  authors/apps/authentication/models.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_endpoints.py
  authors/apps/authentication/tests_/test_model.py
  authors/apps/authentication/tests_/test_user_endpoints.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/utils.py
  authors/apps/authentication/views.py
  authors/apps/core/templates/email.html
  authors/settings.py
  requirements.txt
Labels: finished, reviews required

#14 #162725258: Users should be able to create their profiles
  .DS_Store
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/urls.py
  authors/apps/profiles/__init__.py
  authors/apps/profiles/admin.py
  authors/apps/profiles/apps.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/migrations/__init__.py
  authors/apps/profiles/models.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  authors/apps/utils/custom_permissions/__init__.py
  authors/apps/utils/custom_permissions/permissions.py
  authors/apps/utils/messages.py
  authors/settings.py
  authors/urls.py
  requirements.txt
Labels: finished

#16 # 162725259: Users should be able to create articles
  .DS_Store
  .gitignore
  authors/apps/articles/__init__.py
  authors/apps/articles/admin.py
  authors/apps/articles/apps.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/__init__.py
  authors/apps/articles/models.py
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/__init__.py
  authors/apps/articles/tests/test_models.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/utils.py
  authors/apps/articles/views.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_user_endpoints.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/views.py
  authors/apps/utils/custom_permissions/permissions.py
  authors/apps/utils/messages.py
  authors/settings.py
  authors/urls.py
  requirements.txt
  sample_env.txt
Labels: reviews required

#19 #163298000 Validate username input
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_data.py
  authors/apps/authentication/tests_/test_signup_validation.py
  authors/apps/utils/validators/validation_helpers.py
  sample_env.txt
Labels: finished

#20 #162725270 Users should be able to see estimate reading time for articles
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_models.py
  authors/apps/utils/estimator.py
  authors/apps/utils/tests/test_estimator.py
Labels: finished, reviews required

#21 #162725266 List users functionality
  authors/apps/profiles/renderers.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
Labels: finished

#23 #162725268 Add article pagination support
  authors/apps/articles/paginators.py
  authors/apps/articles/views.py
  authors/settings.py
Labels: finished

#22 #162725271 Enable user to share articles on different platforms
  authors/apps/articles/serializers.py
  authors/apps/articles/views.py
  authors/apps/utils/share_links.py
Labels: finished, reviews required

#25 #162725261 Implement commenting on articles
  .codeclimate.yml
  .travis.yml
  authors/apps/articles/urls.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_data.py
  authors/apps/comments/__init__.py
  authors/apps/comments/admin.py
  authors/apps/comments/apps.py
  authors/apps/comments/migrations/0001_initial.py
  authors/apps/comments/migrations/__init__.py
  authors/apps/comments/models.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/__init__.py
  authors/apps/comments/tests/test_comment_endpoints.py
  authors/apps/comments/tests/test_comment_model.py
  authors/apps/comments/urls.py
  authors/apps/comments/views.py
  authors/apps/utils/custom_permissions/permissions.py
  authors/settings.py
  authors/urls.py
Labels: finished, reviews required

#24 #162725262 Users should be able to like or dislike articles
  authors/apps/articles/migrations/0002_articlelikes.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/utils.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0002_auto_20190124_1345.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_data.py
Labels: finished

#29 #162725272 Users should be able to bookmark articles
  authors/apps/articles/migrations/0003_bookmark.py
  authors/apps/articles/models.py
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_bookmark_endpoints.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/utils/renderers.py
  authors/urls.py
Labels: finished, reviews required

#17 #162725257 Enable social login for the users to the application
  .gitignore
  authors/apps/authentication/register_social.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/social_auth.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_social_auth.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/settings.py
  requirements.txt
  sample_env.txt
Labels: finished, reviews required

#30 #162725263 Users should be able to follow each other
  authors/apps/profiles/migrations/0002_profile_followers.py
  authors/apps/profiles/models.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/__init__.py
  authors/apps/profiles/tests/test_base_class.py
  authors/apps/profiles/tests/test_follow.py
  authors/apps/profiles/tests/tests.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  authors/apps/utils/messages.py
Labels: finished, reviews required

#32 #162725260 Users should be able to rate an article
  authors/apps/articles/migrations/0004_articlerating.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_models.py
  authors/apps/articles/tests/test_rating_endpoint.py
  authors/apps/articles/urls.py
  authors/apps/articles/utils.py
  authors/apps/articles/views.py
  authors/apps/authentication/tests_/test_base_class.py
Labels: finished

#31 #162725264 users should favorite articles
  .codeclimate.yml
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0005_article_favorites.py
  authors/apps/articles/models.py
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/tests.py
  authors/apps/profiles/urls.py
  authors/apps/utils/messages.py
  authors/urls.py
Labels: finished, reviews required

#34 #162725267 Enable users to add tags to their articles
  authors/apps/articles/migrations/0006_article_tags.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_tags.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/urls.py
Labels: finished, reviews required

#33 #162725276 Implement liking of comments
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/comments/admin.py
  authors/apps/comments/commentReplyViews.py
  authors/apps/comments/migrations/0001_initial.py
  authors/apps/comments/models.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/test_comment_endpoints.py
  authors/apps/comments/tests/test_comment_model.py
  authors/apps/comments/urls.py
  authors/apps/comments/utils.py
  authors/apps/comments/views.py
Labels: finished, reviews required

#28 #162725269: Implement search and custom filtering functionality to articles
  authors/apps/articles/filters.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views/bookmark_views.py
  authors/apps/articles/views/views.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/profiles/models.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/views.py
  authors/settings.py
  authors/urls.py
  requirements.txt
Labels: finished

#35 #162725274 Highlight and comment on any text in an article
  authors/apps/authentication/tests_/test_data.py
  authors/apps/comments/migrations/0002_auto_20190129_1211.py
  authors/apps/comments/models.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/test_highlight_comment.py
  authors/apps/comments/views.py
  authors/apps/utils/validators/validation_helpers.py
Labels: finished, reviews required

#18 #162725265 Users should be able to receive notifications
  .gitignore
  authors/apps/articles/views/views.py
  authors/apps/comments/migrations/0002_auto_20190124_1741.py
  authors/apps/comments/migrations/0003_merge_20190129_1525.py
  authors/apps/comments/models.py
  authors/apps/comments/views.py
  authors/apps/core/models.py
  authors/apps/core/templates/notification_email.txt
  authors/apps/notifications/__init__.py
  authors/apps/notifications/apps.py
  authors/apps/notifications/backends.py
  authors/apps/notifications/migrations/0001_initial.py
  authors/apps/notifications/migrations/__init__.py
  authors/apps/notifications/models.py
  authors/apps/notifications/renderers.py
  authors/apps/notifications/serializers.py
  authors/apps/notifications/tests/__init__.py
  authors/apps/notifications/tests/test_base_class.py
  authors/apps/notifications/tests/test_delivery.py
  authors/apps/notifications/tests/test_endpoints.py
  authors/apps/notifications/tests/test_models.py
  authors/apps/notifications/urls.py
  authors/apps/notifications/utils.py
  authors/apps/notifications/views.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/migrations/0003_auto_20190125_1512.py
  authors/apps/profiles/models.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/views.py
  authors/apps/utils/messages.py
  authors/settings.py
  authors/urls.py
Labels: finished, reviews required

#38 #162725273 Users report articles
  authors/apps/articles/admin.py
  authors/apps/articles/migrations/0007_reportarticle.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_models.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views/views.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_data.py
  authors/apps/utils/custom_permissions/permissions.py
  authors/apps/utils/messages.py
  authors/settings.py
Labels: finished, reviews required

#39 #163567754: make page index start at one
  authors/apps/articles/paginators.py
  authors/apps/articles/views/bookmark_views.py
  authors/apps/articles/views/views.py
Labels: finished, reviews required

#40 #163567419 fix login with any of username/password or email/password
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests_/test_base_class.py
  authors/apps/authentication/tests_/test_data.py
  authors/apps/authentication/tests_/test_user_endpoints.py
  authors/apps/utils/validators/validation_helpers.py
Labels: finished, reviews required

#36 #162725275 Comments should track edit history
  authors/apps/comments/commentReplyViews.py
  authors/apps/comments/migrations/0004_historicalcomment.py
  authors/apps/comments/migrations/0005_historicalcommentreply.py
  authors/apps/comments/models.py
  authors/apps/comments/renderers.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/test_edit_history.py
  authors/apps/comments/tests/test_the_comment_endpoints.py
  authors/apps/comments/urls.py
  authors/apps/comments/utils.py
  authors/apps/comments/views.py
  authors/apps/utils/custom_permissions/permissions.py
  authors/settings.py
  requirements.txt
Labels: finished

#41 #163583000 Add authentication to API swagger documentation
  authors/apps/authentication/views.py
  authors/settings.py
  authors/urls.py
Labels: work in progress

#42 #163591958 A following count should return for a given profile
  authors/apps/profiles/serializers.py
Labels: finished, reviews required

#37 #162725277 Enable users to see their reading stats
  authors/apps/articles/migrations/0008_auto_20190130_1041.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views/article_update_view.py
  authors/apps/articles/views/read_stats_views.py
  authors/apps/articles/views/views.py
  authors/apps/profiles/models.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
Labels: finished, reviews required
